public class GeneralProviderContentWrapper {
    
    /*

/**
* @description  Wrapper class for request and response for Inbound callouts from various systems

public without sharing class GeneralProviderContentWrapper 
{
    /**
* @description Error in Response Common

    public class ErrorResponse
    {
        public String error;
    }
        /**
* @description CreateLead_Eterm Request

    public class CreateLead_Eterm
    {
        public Object Eterm_CRM_Lead_Req;
    }
            /**
* @description CreateLead_Online Request

    public class CreateLead_Online
    {
        public String lead_info;
    }
    /**
* @description Create Case Response

    public class CreateCaseResponse
    {
        public String caseNumber;
        public String success;
        public String CreateCaseResponse;
    }
        /**
* @description Create Case Response

    public class CreateLeadResponse
    {
        public String LeadName;
        public String success;
        public String leadId;
    }
            /**
* @description Create Contact Response

    public class CreateContactResponse
    {
        public String contactName;
        public String message;
        public String contactId;
    }
    
     /**
* @description getPolicies API request

    public class getPoliciesReq
    {
        public String PolicyNumber;
    }
    /**
* @description policyStatus API response

    public class GetPolicyResp
    {
        public PolicyDetails_Resp PolicyDetails_Resp;
        public String Message; //OK
        public String Status; //Success
    }
    public class PolicyDetails_Resp
    {
        public PolicyDetails[] PolicyDetails;
    }
    public class PolicyDetails
    {
        public String PolicyStatus; //Not taken Up
        public String PolicyNumber; //10373964
        public String NextPremiumDueDate; //14/01/2011 18:30:00
        public String ClientID; //54269821
        public String EmailID; //stsgchh@iugu.com
        public String HNI; //null
        public String Is_Radiance; //null
        public String PhoneNumber; //9678678987
    }
}

*/

}